#!/bin/bash

DOCKER_HUB_USERNAME=""
PROJECT_NAME="ubuntu"
DOCKER_TAG="latest"

if [ -z DOCKER_HUB_USERNAME]
then
    BASE_IMAGE_NAME="$DOCKER_HUB_USERNAME/$PROJECT_NAME:$DOCKER_TAG"
else
    BASE_IMAGE_NAME="$PROJECT_NAME:$DOCKER_TAG"
fi

WORKSPACE="/workspace"
GPU="all"
